[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
bitcoin_hashes = "0.12.0"
rand = "0.8.5"
bs58 = "0.5.0"
hex = "0.4"
